name: PLAI Actions
on:
  schedule:
    - cron: '0 0 * * MON'  # Runs every Monday at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-predictions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Yarn
        run: npm install -g yarn
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build TypeScript
        run: yarn build
        
      - name: Run prediction script
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: yarn start 